const detailsMovieTypes = {
  GET_MOVIE_BY_ID_START: 'GET_MOVIE_BY_ID_START',
  GET_MOVIE_BY_ID_SUCCESS: 'GET_MOVIE_BY_ID_SUCCESS',
  GET_MOVIE_BY_ID_ERROR: 'GET_MOVIE_BY_ID_ERROR',
  GET_RECOMMENDED_MOVIES_START: 'GET_RECOMMENDED_MOVIES_START',
  GET_RECOMMENDED_MOVIES_SUCCESS: 'GET_RECOMMENDED_MOVIES_SUCCESS',
  GET_RECOMMENDED_MOVIES_ERROR: 'GET_RECOMMENDED_MOVIES_ERROR',
};

export default detailsMovieTypes;
