const favMoviesTypes = {
  ADD_TO_FAV_MOVIES_START: 'ADD_TO_FAV_MOVIES_START',
  ADD_TO_FAV_MOVIES_SUCCESS: 'ADD_TO_FAV_MOVIES_SUCCESS',
  ADD_TO_FAV_MOVIES_ERROR: 'ADD_TO_FAV_MOVIES_ERROR',
  REMOVE_FROM_FAV_MOVIES: 'REMOVE_FROM_FAV_MOVIES',
};

export default favMoviesTypes;
