const types = {
  GET_POPULAR_MOVIES_START: 'GET_MOVIES_START',
  GET_POPULAR_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_POPULAR_MOVIES_ERROR: 'GET_MOVIES_ERROR',
  GET_MOVIES_BY_QUERY_START: 'GET_MOVIES_BY_QUERY_START',
  GET_MOVIES_BY_QUERY_SUCCESS: 'GET_MOVIES_BY_QUERY_SUCCESS',
  GET_MOVIES_BY_QUERY_ERROR: 'GET_MOVIES_BY_QUERY_ERROR',
  GET_MOVIES_BY_QUERY_PAGINATION_START: 'GET_MOVIES_BY_QUERY_PAGINATION_START',
  GET_MOVIES_BY_QUERY_PAGINATION_SUCCESS: 'GET_MOVIES_BY_QUERY_PAGINATION_SUCCESS',
  GET_MOVIES_BY_QUERY_PAGINATION_ERROR: 'GET_MOVIES_BY_QUERY_PAGINATION_ERROR',
  GET_MOVIES_POPULAR_PAGINATION_START: 'GET_MOVIES_BY_QUERY_PAGINATION_START',
  GET_MOVIES_POPULAR_PAGINATION_SUCCESS: 'GET_MOVIES_BY_QUERY_PAGINATION_SUCCESS',
  GET_MOVIES_POPULAR_PAGINATION_ERROR: 'GET_MOVIES_BY_QUERY_PAGINATION_ERROR',
  GET_ALL_GENRES_START: 'GET_ALL_GENRES_START',
  GET_ALL_GENRES_SUCCESS: 'GET_ALL_GENRES_SUCCESS',
  GET_ALL_GENRES_ERROR: 'GET_ALL_GENRES_ERROR',
};

export default types;
